function _swift_knox_using_command
    set -l cmd (commandline -opc)
    if [ (count $cmd) -eq (count $argv) ]
        for i in (seq (count $argv))
            if [ $cmd[$i] != $argv[$i] ]
                return 1
            end
        end
        return 0
    end
    return 1
end
complete -c knox -n '_swift_knox_using_command knox' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox' -f -l version -d 'Show the version.'
complete -c knox -n '_swift_knox_using_command knox' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'list' -d 'Top-level command for listing data.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'home-diag' -d 'Get a Home Diagnostic image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'uma' -d 'Get a Universal Mac Assistant image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'umia' -d 'Get a Universal Mac Internal Assistant image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'umasr' -d 'Get a Universal Mac ASR image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'umiasr' -d 'Get a Universal Mac Internal ASR image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'umr' -d 'Get a Universal Mac Restore image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'umir' -d 'Get a Universal Mac Internal Restore image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'umripsw' -d 'Get a Universal Mac Restore IPSW image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'xip' -d 'Get an XcodeXIP image.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'depdb' -d 'Get a Dependency Database.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'download' -d 'Download a file.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'extract' -d 'Extract a Knox archive.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'raw-request' -d 'Run an authenticated, paginated request to Knox.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'upgrade' -d 'Upgrade to a newer version of this utility.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'ping' -d 'Is server reachable?'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'diagnostics' -d 'Gather diagnostic info.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'generate-completion-script' -d 'Generate shell completion script'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'replace-self' -d 'Replace current binary with a newer version.'
complete -c knox -n '_swift_knox_using_command knox' -f -a 'help' -d 'Show subcommand help information.'
complete -c knox -n '_swift_knox_using_command knox list' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox list' -f -a 'fields' -d 'Fields defined by one pointer type.'
complete -c knox -n '_swift_knox_using_command knox list' -f -a 'pointers' -d 'Pointers matching some criteria.'
complete -c knox -n '_swift_knox_using_command knox list' -f -a 'values' -d 'Unique values for a field in a pointer type.'
complete -c knox -n '_swift_knox_using_command knox list' -f -a 'types' -d 'All pointer types in the space.'
complete -c knox -n '_swift_knox_using_command knox list' -f -a 'spaces' -d 'List all spaces. Admin users only.'
complete -c knox -n '_swift_knox_using_command knox list' -f -a 'help' -d 'Show subcommand help information.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l space -s s -d 'Name of the Knox space to use.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox list fields' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -l latest -s l -d 'Fetch only the one most recent pointer matching.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l space -s s -d 'Name of the Knox space to use.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -r -l earliest -d 'Time range for limiting query results to only the most recently created entries'
complete -c knox -n '_swift_knox_using_command knox list pointers' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l space -s s -d 'Name of the Knox space to use.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox list values' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox list values' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox list values' -f -r -l earliest -d 'Time range for limiting query results to only the most recently created entries'
complete -c knox -n '_swift_knox_using_command knox list values' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l space -s s -d 'Name of the Knox space to use.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox list types' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox list types' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox list types' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox list types' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox list spaces' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox home-diag' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox uma' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox uma' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox umia' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox umia' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox umasr' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox umiasr' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox umr' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox umr' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox umir' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox umir' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox umripsw' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox xip' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox xip' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l abridged -d 'Specify if a full or abridged database should be obtained'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l unabridged -d 'Specify if a full or abridged database should be obtained'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l summary -d 'Specify if a full or abridged database should be obtained'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox depdb' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox download' -f -l raw -d 'Perform a download without AEA decryption'
complete -c knox -n '_swift_knox_using_command knox download' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l saks-client-certificate -d 'Path to a p12 client certificate for use with SAKS'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l saks-certificate-password-file -d 'Path to file containing the password for a client certificate'
complete -c knox -n '_swift_knox_using_command knox download' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l output-file -s o -d 'File name and/or directory to save to.'
complete -c knox -n '_swift_knox_using_command knox download' -f -l sanitize-fields -d 'Sanitize values used as replacements in output file.'
complete -c knox -n '_swift_knox_using_command knox download' -f -l latest -s l -d 'Fetch only the one most recent pointer matching.'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l space -s s -d 'Name of the Knox space to use.'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox download' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox download' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox download' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox download' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox download' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox download' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox download' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox download' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox download' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l create-directory -d 'Create destination directory if it does not exist'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l include -d 'A regular expression for selecting files to extract'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l exclude -d 'A regular expression for excluding files from extraction'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l output-dir -s o -d 'A directory to extract files to'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l latest -s l -d 'Fetch only the one most recent pointer matching.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l space -s s -d 'Name of the Knox space to use.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox extract' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox extract' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox raw-request' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l allow-beta -d 'Allow/disallow Beta <-> Release version upgrades.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l no-allow-beta -d 'Allow/disallow Beta <-> Release version upgrades.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l dry-run -d 'Report, but do not upgrade.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox upgrade' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox ping' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox ping' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox ping' -f -r -l knox-url -s k -d 'The Knox host URL.'
complete -c knox -n '_swift_knox_using_command knox ping' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -l background-networking -d 'Run download at lower priority.'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -r -l thread-count -d 'Number of threads to use while downloading'
complete -c knox -n '_swift_knox_using_command knox diagnostics' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox generate-completion-script' -f -s h -l help -d 'Show help information.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -s f -l output-format -d 'Format for stdout. One of: short, long, json'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -l allow-unstable-unsupported-output-format -d 'Allow non-JSON output to a pipe, etc.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -l keytab -d 'Path to a keytab file.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -l oidc-token -d 'Path to file containing a OIDC token.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -l mtls-cert-path -d 'Path to an mTLS certificate file'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -l mtls-key-path -d 'Path to an mTLS key file'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -l mtls-password-path -d 'Path to an mTLS password file'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -l appleconnect-account -d 'AppleConnect account name.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -l quiet -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -l normal-verbosity -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -l verbose -d 'How much output to stderr.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -s v -d 'Alias for --verbose'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -l enable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -l disable-version-check -d 'Check for a new version of the tool.'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -r -s H -l header -d 'Extra header to include in requests sent to Knox'
complete -c knox -n '_swift_knox_using_command knox replace-self' -f -s h -l help -d 'Show help information.'
