[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1.0
blur = false

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"

size = 14

[keyboard]
bindings = [
  { key = "Space", mods = "Control", chars = "\u0000"},
  { key = "Escape", chars = "\u001B"}
]

[colors]

# Colors (Gruvbox dark)
# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
