import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.75
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"

size = 14

[keyboard]
bindings = [
  { key = "Space", mods = "Control", chars = "\u0000"},
  { key = "Escape", chars = "\u001B"},
]

