[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.72
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"

size = 16

[keyboard]
bindings = [
  { key = "Space", mods = "Control", chars = "\u0000" },
  { key = "Escape", chars = "\u001B" },
]

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

[terminal]
